# [Word2Vec: interpretação da linguagem humana com Word embedding](https://cursos.alura.com.br/course/introducao-word-embedding/)

## Datasets

* [Site NILC USP com Word Embeddings](http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc)

* [Arquivo CBOW 300](https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/cbow_s300.zip)

* [Arquivo Skip-Gram 300](https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/skip_s300.zip)

* [Arquivo treino](https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/treino.csv)

* [Arquivo teste](https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/teste.csv)



In [ ]:
# Abaixo as versões utilizadas no google colab
pip list -v

Package                       Version               Location                                Installer
----------------------------- --------------------- --------------------------------------- ---------
absl-py                       1.4.0                 /usr/local/lib/python3.10/dist-packages pip
alabaster                     0.7.13                /usr/local/lib/python3.10/dist-packages pip
albumentations                1.2.1                 /usr/local/lib/python3.10/dist-packages pip
altair                        4.2.2                 /usr/local/lib/python3.10/dist-packages pip
anyio                         3.6.2                 /usr/local/lib/python3.10/dist-packages pip
appdirs                       1.4.4                 /usr/local/lib/python3.10/dist-packages pip
argon2-cffi                   21.3.0                /usr/local/lib/python3.10/dist-packages pip
argon2-cffi-bindings          21.2.0                /usr/local/lib/python3.10/dist-packages pip
array-record                

In [1]:
!unzip "/content/drive/MyDrive/ml-dataset/word2vec/cbow_s300.zip"
!unzip "/content/drive/MyDrive/ml-dataset/word2vec/skip_s300.zip"

Archive:  /content/drive/MyDrive/ml-dataset/word2vec/cbow_s300.zip
  inflating: cbow_s300.txt           


In [2]:
import pandas as pd

df_treino = pd.read_csv("/content/drive/MyDrive/ml-dataset/word2vec/treino.csv")
df_teste = pd.read_csv("/content/drive/MyDrive/ml-dataset/word2vec/teste.csv")

In [3]:
df_treino.sample(5)

title  \
69954  Programação paralela de Mostra de Teatro traz ...   
47054  Suspeito de matar três israelenses em Tel Aviv...   
20194  Programa de Doria enterra de vez políticas de ...   
74331  Pedro Parente, ex-ministro de FHC, será o novo...   
74330  Defensoria vai investigar irregularidades na s...   

                                                    text        date  \
69954  Além de espetáculos, a programação da MITsp tr...  2015-06-03   
47054  O árabe israelense Nashaat Melhem, 31, suspeit...  2016-08-01   
20194  O prefeito de São Paulo, João Doria (PSDB), an...  2017-06-26   
74331  Pedro Parente, ex-ministro da Casa Civil do go...  2016-05-19   
74330  A Defensoria Pública do Ceará vai investigar a...  2015-05-13   

        category subcategory  \
69954  ilustrada         NaN   
47054      mundo         NaN   
20194  cotidiano         NaN   
74331    mercado         NaN   
74330  cotidiano         NaN   

                                                    link  
69954  http://www1.folha.uol.com.br/ilustrada/2015/03...  
47054  http://www1.folha.uol.com.br/mundo/2016/01/172...  
20194  http://www1.folha.uol.com.br/cotidiano/2017/06...  
74331  http://www1.folha.uol.com.br/mercado/2016/05/1...  
74330  http://www1.folha.uol.com.br/cotidiano/2015/05...

In [4]:
df_teste.sample(5)

title  \
19716  \n\t\tApós prisões de grupo, ministro diz que ...   
5530   Palmeiras confirma contratação de Leandro Alme...   
4783   Odebrecht está prestes fechar renegociação de ...   
18211  \n\t\tAbucheos contra Temer y un show de samba...   
353    Na festa, campeão mundial Mineirinho fala em v...   

                                                    text        date category  \
19716  GABRIEL MASCARENHAS DE BRASÍLIA  O ministro da...  2016-07-21  esporte   
5530   Dois dias antes do clássico contra o São Paulo...  2015-06-26  esporte   
4783   A renegociação da Odebrecht para alongar a dív...  2016-11-04  colunas   
18211  DE RÍO  La ceremonia de apertura de los Juegos...  2016-08-09  esporte   
353    O jogo parecia ganho quando cheguei à praia de...  2015-12-19  esporte   

            subcategory                                               link  
19716  olimpiada-no-rio  http://www1.folha.uol.com.br/esporte/olimpiada...  
5530                NaN  http://www1.folha.uol.com.br/esporte/2015/06/1...  
4783      monicabergamo  http://www1.folha.uol.com.br/colunas/monicaber...  
18211  olimpiada-no-rio  http://www1.folha.uol.com.br/esporte/olimpiada...  
353                 NaN  http://www1.folha.uol.com.br/esporte/2015/12/1...

In [5]:
df_teste.iloc[643].title

'Somos todos imprevisíveis'

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

texto = [
    "tenha um bom dia",
    "tenha um péssimo dia",
    "tenha um ótimo dia",
    "tenha um dia ruim"
]

vec = CountVectorizer()
vec.fit(texto)

CountVectorizer()

In [7]:
vec.vocabulary_

{'tenha': 4, 'um': 5, 'bom': 0, 'dia': 1, 'péssimo': 2, 'ótimo': 6, 'ruim': 3}

In [8]:
vetor_bom = vec.transform(["bom"])
print(vetor_bom.toarray())

[[1 0 0 0 0 0 0]]


In [9]:
vetor_otimo = vec.transform(["ótimo"])
print(vetor_otimo.toarray())

[[0 0 0 0 0 0 1]]


In [10]:
vetor_pessimo = vec.transform(["péssimo"])
print(vetor_pessimo.toarray())

[[0 0 1 0 0 0 0]]


In [11]:
with open("cbow_s300.txt") as f:
  for linha in range(10):
    print(next(f))

929606 300

</s> -0.001667 -0.000158 -0.000026 0.001300 -0.000796 0.001527 0.000046 0.000584 0.000449 -0.000100 0.000353 0.001251 0.001069 0.000506 0.000574 0.000838 -0.000930 -0.001220 0.000317 0.001315 -0.001120 0.001373 -0.000040 -0.001580 0.000421 -0.000667 -0.001556 -0.000746 0.001604 0.001157 -0.000027 0.000354 0.000358 -0.000527 -0.000573 -0.001512 -0.001557 -0.001637 0.001617 -0.001511 -0.001022 -0.001426 0.001086 -0.001033 0.000593 0.000724 0.000627 -0.000450 -0.001140 0.000333 0.000524 0.001541 0.000284 0.000617 -0.000807 -0.000088 -0.000364 0.001126 -0.001230 -0.001138 -0.001280 0.001330 0.001257 0.000576 0.000764 0.000684 0.001008 -0.000215 -0.000629 -0.001228 -0.001557 -0.000311 -0.000246 0.000045 0.001136 -0.000645 -0.000549 0.001099 0.000858 -0.000886 0.000553 0.000303 0.001433 0.000732 0.001321 -0.000894 -0.000700 -0.000661 -0.001484 -0.000950 -0.001556 -0.000809 0.000348 -0.000068 0.000724 -0.000569 -0.000161 -0.001628 -0.001437 -0.000259 -0.000296 -0.001571 0.000149 0

In [12]:
from gensim.models import KeyedVectors

modelo = KeyedVectors.load_word2vec_format("cbow_s300.txt")

In [13]:
vector = modelo.get_vector("china")
print(len(vector))
vector

300


array([-1.49033e-01,  1.26020e-01,  2.17628e-01,  1.82684e-01,
        1.65151e-01, -1.59660e-01, -2.34411e-01,  6.00570e-02,
        8.03680e-02,  2.87578e-01, -4.81100e-03, -5.68800e-02,
        2.15676e-01,  8.65540e-02,  1.25983e-01,  3.36157e-01,
       -1.83254e-01, -1.18499e-01,  1.13010e-02,  1.03814e-01,
        9.37640e-02,  2.90178e-01, -1.64395e-01, -1.13300e-02,
       -1.80676e-01, -1.15820e-02,  1.08728e-01,  1.65898e-01,
        9.37900e-02,  2.66767e-01, -1.29890e-02,  9.16030e-02,
        2.21292e-01, -1.36497e-01, -4.26350e-02, -1.30038e-01,
        2.17067e-01, -1.01963e-01, -3.70960e-02,  1.42155e-01,
        3.41109e-01,  2.46560e-01,  1.27458e-01,  5.72360e-02,
       -1.47962e-01, -1.60290e-02,  1.86533e-01,  7.71550e-02,
       -3.50024e-01, -4.06085e-01,  1.67131e-01, -4.75230e-02,
        5.13780e-02, -1.28224e-01,  1.06580e-02, -2.92652e-01,
        1.40540e-01, -4.57049e-01,  1.31094e-01,  2.03234e-01,
        2.94019e-01,  7.38370e-02,  1.11554e-01, -1.642

In [14]:
modelo.most_similar("china")

[('rússia', 0.7320705056190491),
 ('índia', 0.7241616249084473),
 ('tailândia', 0.701935887336731),
 ('indonésia', 0.6860769987106323),
 ('turquia', 0.6741335988044739),
 ('malásia', 0.6665689945220947),
 ('mongólia', 0.6593616008758545),
 ('manchúria', 0.658184826374054),
 ('urss', 0.6581669449806213),
 ('grã-bretanha', 0.6568097472190857)]

In [15]:
modelo.most_similar("itália")

[('frança', 0.7983608841896057),
 ('grécia', 0.7547340989112854),
 ('espanha', 0.7417078018188477),
 ('holanda', 0.7343162298202515),
 ('grã-bretanha', 0.728174090385437),
 ('inglaterra', 0.7172061204910278),
 ('bélgica', 0.7155542373657227),
 ('alemanha', 0.7135661840438843),
 ('suécia', 0.6831520199775696),
 ('áustria', 0.6822685599327087)]

In [16]:
modelo.most_similar(positive=["brasil", "argentina"])

[('chile', 0.6781662702560425),
 ('peru', 0.634803295135498),
 ('venezuela', 0.6273865699768066),
 ('equador', 0.6037014126777649),
 ('bolívia', 0.6017141342163086),
 ('haiti', 0.5993806719779968),
 ('méxico', 0.596230685710907),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.590367317199707),
 ('japão', 0.5893509387969971)]

In [17]:
# nuvens -> nuvem: estrelas -> estrela
# nuvens + estrela - nuvem = estrelas

modelo.most_similar(positive=["nuvens", "estrela"], negative=["nuvem"])

[('estrelas', 0.5497430562973022),
 ('plêiades', 0.3791979253292084),
 ('colinas', 0.3746805489063263),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.37341946363449097),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727400779724),
 ('cigarras', 0.36065396666526794),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [18]:
modelo.most_similar(positive=["médico", "mulher"], negative=["homem"])

[('enfermeira', 0.6180862784385681),
 ('psicóloga', 0.47447532415390015),
 ('dama-de-companhia', 0.47382354736328125),
 ('esposa', 0.46559134125709534),
 ('parteira', 0.46362870931625366),
 ('mãe', 0.45817679166793823),
 ('governanta', 0.45722925662994385),
 ('madrasta', 0.4569782614707947),
 ('menina', 0.44435903429985046),
 ('filha', 0.44341111183166504)]

In [19]:
modelo.most_similar(positive=["professor", "mulher"], negative=["homem"])

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978230893611908),
 ('ex-aluna', 0.4884248673915863),
 ('namorada', 0.4737858772277832),
 ('enfermeira', 0.4728144407272339),
 ('filha', 0.467373788356781),
 ('irmã', 0.4584590792655945),
 ('ex-namorada', 0.45824769139289856),
 ('ex-professora', 0.45104706287384033)]

In [20]:
df_treino.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [21]:
"Texto Exemplo, 1234".split()

['Texto', 'Exemplo,', '1234']

In [22]:
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [23]:
import nltk
import string

def tokenizador(texto):
  texto = texto.lower()
  lista_alfanumerico = []

  for token in nltk.word_tokenize(texto):
    if token in string.punctuation:
      continue
    lista_alfanumerico.append(token)
  return lista_alfanumerico

tokenizador("Texto Exemplo, 1234")

['texto', 'exemplo', '1234']

In [27]:
import numpy as np

def combinacao_vetores_por_soma(palavras_numeros):
  vetor_resultante = np.zeros(300)
  for token in palavras_numeros:
    vetor_resultante += modelo.get_vector(token)
  return vetor_resultante

In [29]:
palavras_numeros = tokenizador("texto exemplo")
vetor_texto = combinacao_vetores_por_soma(palavras_numeros)
print(len(vetor_texto))
print(vetor_texto)

300
[ 1.68316003e-01  4.17804003e-01 -1.33144002e-01  6.29795998e-01
 -3.51209987e-01 -1.83245994e-01  5.53643979e-01  3.56189996e-01
 -2.50159986e-02 -2.10527996e-01  2.07247000e-01  3.38050000e-01
 -5.46640009e-02  1.30016997e-01 -9.87979919e-02  1.46000013e-02
 -8.24196965e-01  1.31566003e-01  2.35303007e-01 -3.22570056e-02
 -6.90304980e-01 -1.76500000e-01 -1.14080012e-02  1.43174008e-01
  1.17624998e-01 -3.34087998e-01 -3.99442017e-01 -1.16655000e-01
 -1.29959993e-02  2.04947002e-01  1.43737005e-01 -3.55122998e-01
 -6.84799999e-03 -4.15549995e-02  1.15014996e-01  2.93223999e-01
  3.72527003e-01  4.77150992e-01 -1.79260001e-02  2.61502996e-01
 -1.48381008e-01  3.36210015e-01  3.90650004e-01  4.04953010e-01
 -4.27010003e-02  2.52546994e-01  1.90923998e-01  2.67074004e-01
 -5.50239999e-02  1.33014001e-01 -4.69440073e-02  1.19436000e-01
  1.55391991e-01 -3.72460000e-02 -2.94050999e-01 -6.50180001e-02
  1.86276998e-01  3.86574991e-01 -4.11222987e-01 -2.04502001e-01
 -6.80240095e-02  1.1

In [31]:
try:
  palavras_numeros = tokenizador("texto caelumx")
  vetor_texto = combinacao_vetores_por_soma(palavras_numeros)
except Exception as ex:
  # A função lança erro de tentar buscar um vetor de uma palavra que não existe
  print(f"Erro: {ex}")

Erro: "Key 'caelumx' not present"


In [34]:
# Quando é zero no local de palavras desconhecidas, funciona
palavras_numeros = tokenizador("texto 0000000")
vetor_texto = combinacao_vetores_por_soma(palavras_numeros)
print(vetor_texto)

[-0.31464899  0.42469701 -0.274152   -0.05606502 -0.32162799 -0.56328803
 -0.129173   -0.15028602  0.16173099  0.475734    0.44124999  0.399354
 -0.345038    0.021382   -0.07489699 -0.300621   -0.31287     0.61843699
 -0.45570599 -0.51683201  0.025178   -0.80050102 -0.02149601  0.247554
  0.67282599  0.68325499 -0.682273    0.044066   -0.17267499  1.09891598
  0.80378099 -0.18135    -0.502466   -0.395125   -0.10440401  0.34390201
  0.30856101  0.82802302  0.64049402  0.45028    -0.063795    0.210197
  0.053633   -0.16787101  0.66719999 -0.22004199 -0.17332399 -0.16956799
 -0.094044    0.369799    0.329293    0.299922    0.35769397 -0.145999
 -0.701936   -0.45240301  0.272447    0.01542899  0.82466999 -0.344318
 -0.75626498 -0.11828     0.39875799  0.048345    0.12320599 -0.59117401
 -0.20867501  0.14465499  0.09837401  0.31015499  0.28320699 -0.23263801
  0.33054199 -0.34865699  0.48431398 -0.284722   -0.164483    0.270408
  0.44010001 -0.467027    0.223717   -0.145918    0.088119   -0

In [35]:
def combinacao_vetores_por_soma(palavras_numeros):
  vetor_resultante = np.zeros(300)
  for token in palavras_numeros:
    try:
      vetor_resultante += modelo.get_vector(token)
    except KeyError:
      if token.isnumeric():
        token = "0"*len(token)
        vetor_resultante += modelo.get_vector(token)
      else:
        vetor_resultante += modelo.get_vector("unknown")

  return vetor_resultante

In [37]:
palavras_numeros = tokenizador("texto caelumx")
vetor_texto = combinacao_vetores_por_soma(palavras_numeros)
print(len(vetor_texto))
print(vetor_texto)

300
[ 4.04902007e-01  1.61033005e-01 -1.28350001e-01  4.63957988e-01
 -3.79070006e-02  9.79099981e-02  6.06219992e-02  2.50669867e-02
 -1.45315003e-01 -1.20187001e-01 -1.45029984e-02 -3.97820026e-02
 -5.53439990e-01  3.39491010e-01  4.74720001e-02  2.32610006e-01
 -7.91507989e-01  7.62100518e-03 -4.30413000e-01 -1.62210986e-01
 -1.36736006e-01 -2.92862996e-01 -7.81050026e-02  4.56106991e-01
 -1.08597010e-01 -1.72903001e-01 -3.94289017e-01 -7.94299692e-03
  1.54560007e-01 -1.81829929e-02 -1.44808993e-01 -1.92361996e-01
  5.27470000e-02  2.77960012e-02  3.75599414e-03  2.15162002e-01
  2.41512008e-01  2.07674988e-01  1.77449007e-01  2.00845003e-01
  1.08239995e-02 -1.03557003e-01  4.52470034e-02  3.54460012e-02
  2.74897987e-01 -7.71570001e-02  4.26173002e-01  4.57773015e-01
  2.98846003e-01  2.85166003e-01  1.75556996e-01  1.93372004e-01
 -2.64183000e-01  1.87287997e-01  2.00636007e-01 -1.48244001e-01
  1.16369996e-01  5.01876995e-01 -2.73249969e-02 -3.36082000e-01
 -1.06219009e-01  4.2

In [39]:
len(df_treino.title)

90000

In [41]:
def get_matriz(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x, y))
  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_vetores_por_soma(palavras_numeros)
  return matriz

matriz_treino = get_matriz(df_treino.title)
matriz_teste = get_matriz(df_teste.title)
print(matriz_treino.shape)
print(matriz_teste.shape)

(90000, 300)
(20513, 300)


In [45]:
print(sorted(df_treino.category.unique()))
print(sorted(df_teste.category.unique()))

['colunas', 'cotidiano', 'esporte', 'ilustrada', 'mercado', 'mundo']
['colunas', 'cotidiano', 'esporte', 'ilustrada', 'mercado', 'mundo']


In [46]:
from sklearn.linear_model import LogisticRegression

modelo_lr = LogisticRegression()
modelo_lr.fit(matriz_treino, df_treino.category)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [73]:
modelo_lr = LogisticRegression(max_iter=200)
modelo_lr.fit(matriz_treino, df_treino.category)

LogisticRegression(max_iter=200)

In [74]:
# Número de iterações para convergir
modelo_lr.n_iter_

array([118], dtype=int32)

In [75]:
# Pontuação geral de todas categorias
modelo_lr.score(matriz_teste, df_teste.category)

0.7957880368546775

In [76]:
from sklearn.metrics import classification_report

label_prevista = modelo_lr.predict(matriz_teste)
class_report = classification_report(df_teste.category, label_prevista)
print(class_report)

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [52]:
from sklearn.dummy import DummyClassifier

dummy_classifier = DummyClassifier()
dummy_classifier.fit(matriz_treino, df_treino.category)
label_prevista_dc = dummy_classifier.predict(matriz_teste)

class_report_dc = classification_report(df_teste.category, label_prevista_dc)
print(class_report_dc)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     colunas       0.30      1.00      0.46      6103
   cotidiano       0.00      0.00      0.00      1698
     esporte       0.00      0.00      0.00      4663
   ilustrada       0.00      0.00      0.00       131
     mercado       0.00      0.00      0.00      5867
       mundo       0.00      0.00      0.00      2051

    accuracy                           0.30     20513
   macro avg       0.05      0.17      0.08     20513
weighted avg       0.09      0.30      0.14     20513



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [64]:
modelo_skipgram = KeyedVectors.load_word2vec_format("skip_s300.txt")

In [67]:
def combinacao_vetores_por_soma(palavras_numeros, modelo):
  vetor_resultante = np.zeros(300)
  for token in palavras_numeros:
    try:
      vetor_resultante += modelo.get_vector(token)
    except KeyError:
      if token.isnumeric():
        token = "0"*len(token)
        vetor_resultante += modelo.get_vector(token)
      else:
        vetor_resultante += modelo.get_vector("unknown")

  return vetor_resultante

def get_matriz(textos, modelo):
  x = len(textos)
  y = 300
  matriz = np.zeros((x, y))
  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_vetores_por_soma(palavras_numeros, modelo)
  return matriz

In [70]:
matriz_treino_skipgram = get_matriz(df_treino.title, modelo_skipgram)
matriz_teste_skipgram = get_matriz(df_teste.title, modelo_skipgram)

In [78]:
# Previsão
modelo_lr_skipgram = LogisticRegression(max_iter=1000)
modelo_lr_skipgram.fit(matriz_treino_skipgram, df_treino.category)
label_previsao_skipgram = modelo_lr_skipgram.predict(matriz_teste_skipgram)
class_report_skipgram = classification_report(df_teste.category, label_previsao_skipgram)
print(class_report_skipgram)

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.63      0.81      0.70      1698
     esporte       0.93      0.89      0.91      4663
   ilustrada       0.15      0.91      0.26       131
     mercado       0.84      0.81      0.83      5867
       mundo       0.76      0.86      0.80      2051

    accuracy                           0.81     20513
   macro avg       0.69      0.83      0.71     20513
weighted avg       0.84      0.81      0.82     20513



In [79]:
print("CBOW")
print(class_report)
print("Skip-Gram")
print(class_report_skipgram)
print("Dummy")
print(class_report_dc)

CBOW
              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513

Skip-Gram
              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.63      0.81      0.70      1698
     esporte       0.93      0.89      0.91      4663
   ilustrada       0.15      0.91      0.26       131
     mercado       0.84      0.81      0.83      5867
       mundo       0.76      0.86      0.80      2051

    accuracy                           0.81     20513
   macro